config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "home#home"
  root "pages#home"
  ### Employees ###
  # get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'employees/:id', to: 'pages#show_employee'
  post 'employees', to: 'pages#create_employee'
  get 'employees_new', to: 'pages#new_employee'
  get 'employee_edit/:id', to: 'pages#edit_employee'
  patch 'employee_update/:id', to: 'pages#update_employee'
  delete 'employee_destroy/:id', to: 'pages#destroy_employee'
  ### Departments ###
  get 'departments', to: 'pages#departments'
  get '/department/new', to: 'pages#new_department'
  post 'department_create', to: 'pages#create_department'
  get 'departments/:id', to: 'pages#show_department'
  get 'department_edit/:id', to: 'pages#edit_department'
  patch 'department_update/:id', to: 'pages#update_department'
  delete 'department_destroy/:id', to: 'pages#destroy_department'
  ### Projects ###
  resources :projects
  ### Current user ###
  get 'edit_current_user', to: 'current_user#edit_current_user'
  patch 'update_current_user', to: 'current_user#update_current_user'

  ### APIS => api/v1 ###
  namespace :api do
    namespace :v1 do
      get '/index', to: 'user#index'
      post '/user', to: 'user#user_info'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department, required: false
  has_one_attached :image
  has_many_attached :pictures
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee", optional: true
  validates :name, presence: true
  validates :age, numericality: { only_integer: true }, comparison: { greater_than: 17 }
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image, :dependent => :destroy

  def image_as_thumbnail
    image.variant(resize_to_limit: [300, 300]).processed
  end
end

app/controllers/api/v1/user_controller.rb
class Api::V1::UserController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render json: { business: "Haha" }, status: 200
  end

  def user_info
    @user = User.find_by(id: paramable[:id])
    
    if @user.nil?
      render json: { error: "Invalid id"}, status: 201
    else
      # render json: { user: @user }, status: 200
      
      render json: { user: UserSerializer.new(@user, root: false) }, status: 200
      
    end
  end

  private

  def paramable
    params.require(:user).permit(:id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/current_user_controller.rb
class CurrentUserController < ApplicationController
  def edit_current_user
    @user = current_user
  end

  def update_current_user
    @user = User.find(current_user.id)
    if(!params[:user][:image].nil?)
      @user.update(first_name: user_params[:first_name], last_name: user_params[:last_name], age: user_params[:age], full_name: "#{user_params[:first_name]} #{user_params[:last_name]}", image: user_params[:image])
    else
      @user.update(first_name: user_params[:first_name], last_name: user_params[:last_name], age: user_params[:age], full_name: "#{user_params[:first_name]} #{user_params[:last_name]}")
    end
    # @user.update(full_name: "#{user_params[:first_name]} #{user_params[:last_name]}")
    if @user.save
      UserMailer.with(user: current_user).user_logedin.deliver_later
      redirect_to "/about", notice: "You Updated your details !!"
    else
      render :edit_current_user, alert: "Your details wasn't Updated !!"
    end
  end

  private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home departments]
  def home
    @employees = Employee.all.includes(:department)
  end

  def new_employee
    @employee = Employee.new
  end

  def create_employee
    @employee = Employee.new(employee_create_params)
    if @employee.save
      redirect_to root_path, notice: "You created a employee !!"
    else
      render :new_employee, alert: "Your employee wasn't created !!"
    end
  end

  def about
    @user = current_user
  end

  def show_employee
    @employee = Employee.find_by(id: params['id'])
    @department = @employee['department_id'] != nil ? Department.find_by(id: @employee['department_id']) : 'NA'
    debugger
  end

  def destroy_employee
    @emp = Employee.find_by(id: params['id'])
    @emp.destroy
    @chk = Employee.find_by(id: params['id'])
    if(!@chk.present?)
      redirect_to root_path, alert: "You deleted a employee !!"
    end
  end

  def edit_employee
    @employee = Employee.find_by(id: params['id'])
  end

  def update_employee
    @employee = Employee.find_by(id: params['id'])
    data = employee_params
    @employee.update(name: data['name'], age: data['age'], department_id: data['department_id'])
    if @employee.save
      redirect_to "/employees/#{params['id']}", notice: "You Updated a employee !!"
    else
      render :edit_employee, alert: "Your employee wasn't Updated !!"
    end
  end

  def departments
    @departments = Department.all
  end

  def new_department
    @department = Department.new
  end

  def create_department
    @department = Department.new(department_params)
    if @department.save
      redirect_to '/departments', notice: "You created a department !!"
    else
      render :new_department, alert: "Your department wasn't created !!"
    end
  end

  def show_department
    @department = Department.find_by(id: params['id'])
  end

  def edit_department
    @department = Department.find_by(id: params['id'])
  end

  def update_department
    @department = Department.find_by(id: params['id'])
    data = department_params
    @department.update(name: data['name'])
    if @department.save
      redirect_to "/departments/#{params['id']}", notice: "You Updated a employee !!"
    else
      render :edit_department, alert: "Your employee wasn't Updated !!"
    end
  end

  def destroy_department
    @dept = Department.find_by(id: params['id'])
    @dept.destroy
    @chk = Department.find_by(id: params['id'])
    if(!@chk.present?)
      redirect_to '/departments', alert: "You deleted a department !!"
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :age, :department_id)
  end

  def employee_create_params
    params.require(:employee).permit(:name, :age, :department_id, :image, pictures: [])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @val = Project.new(process_params)
    if @val.save
      redirect_to projects_path
    else
      render :new
    end

  end

  def show
    @project = Project.find(params['id'])
  end

  def edit
    @project = Project.find(params['id'])
  end

  def update
    @project = Project.find(params['id'])
    @project.update(process_params)
    if @project.save
      redirect_to "/projects/#{params['id']}"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params['id'])
    @project.destroy
    @chk = Project.find_by(id: params['id'])
    if (!@chk.present?)
      redirect_to projects_path
    end
  end

  private

  def process_params
    params.require(:project).permit(:name)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entry)
      else
        redirect_to navigation_location
      end
    end
  end
  
  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/current_user/edit_current_user.html.erb
<div class="container">  
  <div class="d-flex justify-content-center">
    <%= form_with url: update_current_user_path(@user), method: :patch, model: @user do |f|%>
      <div class="mb-3">
        <% if !@user.image.blank? %>
          <div class="d-flex justify-content-center mb-3 mt-3">
            <%= image_tag(@user.image, class: "profile_image")%>
          </div>
        <% end %>
        <div class="d-flex justify-content-center mb-3 mt-3">
          <%= f.file_field :image%>
        </div>
      </div>
      <div class="mb-3">
        <%= label_tag 'First name: ', nil, class: "form-label"%>
        <%= f.text_field :first_name, class: "form-control"%>
      </div>
      <div class="mb-3">
        <%= label_tag 'Last name: ', nil, class: "form-label"%>
        <%= f.text_field :last_name, class: "form-control"%>
      </div>
      <div>
        <%= label_tag 'Age: ', nil, class: "form-label"%>
        <%= f.number_field :age, class: "form-control"%>
      </div>
      
      <div class="d-flex justify-content-center mt-4">
        <%= submit_tag 'Update', class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice %>  
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-gray-100 p-6 px-3">
  <div class="container-fluid flex items-center">
    <%= link_to "Preet's App", root_path, class: '"font-semibold text-xl tracking-tight"'%>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="navbarSupportedContent">
      <ul class="flex text-sm lg:flex-grow items-center ml-5">
        <li class="mr-3 items-center">
          <%= link_to "Home", root_path, class: 'block lg:inline-block lg:mt-0 text-gray-700 hover:text-black cursor-pointer'%>
        </li>
        <li class="mr-3 items-center">
          <%= link_to "About", '/about', class: 'block lg:inline-block lg:mt-0 text-gray-700 hover:text-black cursor-pointer'%>
        </li>
        
      </ul>
      <ul class="navbar-nav">
        <%= render "user/session_manager"%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udemytutesapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/alerts'%>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">  
  <div class="d-flex justify-content-center">
    <div class="d-flex">
      <h3>Welcome</h3>
    </div>
    <div class="container">
      <div class="d-flex justify-content-center">
        <div class="m-3">
          <div class="mb-3 d-flex justify-content-center">
            <% if !@user.image.blank? %>
              <div class="profile_image">
                <%= image_tag(@user.image, class: "profile_image") %>
              </div>
            <% end %>
          </div>
          <div class="mb-3 d-flex justify-content-center">
            <%= @user.email %>
          </div>
          <div class="mb-3 d-flex justify-content-center">
            <p class="text-black-50"><%= @user.id %>#<%= @user.full_name %></p>
          </div>
          <div class="mt-2 d-flex justify-content-center">
            <%= link_to "Edit", edit_current_user_path, class: "btn btn-dark" %>
          </div>
        </div>
      </div>
    <div>
  </div>
  <div>
    <%= button_tag "test", class: "btn btn-dark text-black hover:text-white", onclick: "test_post_request(this)"%>
  </div>
</div>
<script>
  function test_click(elem){
    console.log(elem)
    $.ajax({
    type: "GET",
    url: "/api/v1/index",
    success: function(data) {
      console.log(data)
    }
  });
  }

  function test_post_request(elem){
    console.log(elem)
    $.post('/api/v1/user', {category:'client', type:'premium'}, function(data){ 
      console.log(data)
    });
  }
</script>

app/views/pages/departments.html.erb
<h1>Departments page</h1>
<%= link_to 'New depatment', '/department/new'%>
<% @departments.each do |dept|%>
  <p>
    <%="[#{dept.id}]"%>
    <%= link_to "#{dept.name}", "/departments/#{dept.id}"%>
  </p>
<% end %>

app/views/pages/edit_department.html.erb
<h1>Edit department page</h1>
<%= form_with url: "/department_update/#{@department.id}", method: :patch, model: @department do |f|%>
  <%= "Name: "%>
  <%= f.text_field :name%>
  <%= f.submit%>
<% end %>

app/views/pages/edit_employee.html.erb
<h1>Edit employee</h1>

<%= form_with url: "/employee_update/#{@employee.id}", method: :patch, model: @employee  do |f| %>
  <%= "Name: "%>
  <%= f.text_field :name %>
  <%= "Age: "%>
  <%= f.number_field :age %>
  <%= "Department Id*: "%>
  <%= f.number_field :department_id%>
  <%= f.submit %>
<% end %>

app/views/pages/home.html.erb
<h1>This is the Home page.</h1>
<div class="d-flex gap-3 my-3">
  <%= button_to "New Employee", employees_new_path, :method => :get, class: "btn btn-primary bg-gray-200 text-gray-800" %>
  <%= button_to "Departments", '/departments', :method => :get, class: "btn btn-secondary bg-gray-200 text-gray-800" %>
</div>
<% @employees.each do |emp|%>
  <p>
    <%= "[#{emp.id}]" %> 
    <%= link_to "#{emp.name}", "/employees/#{emp.id}" %> 
    <%="#{emp.age == '' ? 'NA' : emp.age}"%> 
    <%="#{emp.department_id == nil ? 
      '' 
      : 
      (emp.department.name)
    }"%> 
  </p>
<% end %>

app/views/pages/new_department.html.erb
<h1>Create department page</h1>
<%= form_with url: '/department_create', method: :post, model: @department do |f|%>
  <%= "Name: "%>
  <%= f.text_field :name%>
  <%= f.submit %>
<% end %>

app/views/pages/new_employee.html.erb
<h1>Create new employee</h1>

<%= simple_form_for(@employee) do |f| %>
  <%= f.input :name %>
  <%= f.label :image%>
  <%= f.file_field :image%>
  <%= f.label :pictures%>
  <%= f.file_field :pictures, multiple: true%>
  <%= f.input :age %>
  <%= f.input :department_id%>
  <%= f.submit %>
<% end %>

app/views/pages/show_department.html.erb
<h1>Department detail page</h1>
<%= image_tag(@department.image) %>
<p><%= "[#{@department.id}]"%></p>
<p><%= "#{@department.name}"%></p>
<%= link_to "Edit", "/department_edit/#{@department.id}"%>
<%= button_to "Destroy", action= "/department_destroy/#{@department.id}", :method => :delete %>

app/views/pages/show_employee.html.erb
<h1>Employee detail page.</h1>
<p><%= "Id: #{@employee.id}" %></p>
<p><%= "Name: #{@employee.name}" %></p>
<p><%= "Age: #{@employee.age}" %></p>
<p><%= "Department: #{@employee.department_id != nil ? @department.name : 'NA'}" %></p>
<%= link_to "Edit", "/employee_edit/#{@employee.id}"%>
<%= button_to "Destroy", action= "/employee_destroy/#{@employee.id}", :method => :delete %>

app/views/projects/edit.html.erb
<h1>Project edit page</h1>
<%= form_with model: @project do |f|%>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name%>
  <%= f.submit %>
<%end%>

app/views/projects/index.html.erb
<h1>Projects page </h1>
<%= link_to "Create Project", "/projects/new"%>
<% @projects.each do |proj|%>
  <p>
    <%= "[#{proj.id}]"%>
    <%= link_to "#{proj.name}", "/projects/#{proj.id}"%>
  </p>
<%end%>

app/views/projects/new.html.erb
<h1>Create New Project</h1>
<%= form_with model: @project do |f|%>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name%>
  <%= f.submit %>
<%end%>

app/views/projects/show.html.erb
<h1>Project detail page</h1>
<p><%= "#{@project.id}"%></p>
<p><%= "#{@project.name}"%></p>
<%= link_to "Edit project", "/projects/#{@project.id}/edit"%>
<p></p>
<%= button_to "Delete", action= "/projects/#{@project.id}", :method => :delete %>

app/views/user/_session_manager.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      User
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"%></li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Sign up", new_user_registration_path, class: 'nav-link'%>
  </li>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: 'nav-link'%>
  </li>
<% end %>